### ISSUE TITLE
Xdebug?

### ISSUE THREAD

**Issue by medj** [sergeyklay/phalcon-compose#10]
Is it possible to provide a guide on how to enable xdebug. It says its included but I don't see any reference to it.

**Comment by sergeyklay** [comment]
Hello @medj
I'll try to sort out ASAP.

**Comment by medj** [comment]
Just to give you an idea of what I tried. In my docker-compose.yml, I added an environment configuration which I saw somewhere on stackoverflow. 

```
services:
  application:
    build: containers/core
    container_name: phalcon.compose.volume
    volumes:
      - ./application:/var/www/phalcon
      - ./cache:/var/cache/phalcon
      - ./logs:/var/log/phalcon
    tty: true
    environment:
        XDEBUG_CONFIG: remote_host=172.18.0.7 remote_port=9002
```

However, after checking my `phpinfo`, the port didn't seem to change.

I guess I still need to brush up on docker-compose. When I `build`, does it take my new settings in this file into account?

Also, if I need to make changes to the php.ini file in the future, what is the correct way to do such a thing?

And lastly, I notice the `public` folder in `application`. Is there a way to change things so that it would use `public_html` instead?
